cfr:
  cfr_auto_command_client:
    ros__parameters:
      host_ip: "192.168.1.2"
      # host_ip: "localhost"
      command_port: "10001"
      commands:
        - PSTATE
        - MODE
        - BEACONS
        - NYPAUTO,1
        - INIT
        - PSTATE
        - PSTATE
        - BLADEANG,10
        - FB,1
        - START
        - PSTATE
        - CTRL,0,0,0,0
        - PSTATE
