cfr:
  path_tracker:
    ros__parameters:
      commands:
        - PSTATE
        - MODE
        - BEACONS
        - NYPAUTO,1
        - INIT
        - PSTATE
        - PSTATE
        - BLADEANG,10
        - FB,1
        - START
        - PSTATE
        - CTRL,0,0,0,0
        - PSTATE