controller_manager:
  ros__parameters:
    update_rate: 10  # Hz

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    blades_velocity_controller:
      type: velocity_controllers/JointGroupVelocityController

blades_velocity_controller:
  ros__parameters:
    joints:
      - right_blade_joint
      - left_blade_joint