<?xml version="1.0"?>
<robot name="cfr" xmlns:xacro="http://ros.org/wiki/xacro">

    <xacro:include filename="$(find cfr_description)/urdf/laser.urdf.xacro" />

    <!-- 2D laser position -->
    <xacro:property name="cfr_laser_dx" value="0.725" />
    <xacro:property name="cfr_laser_dy" value="0.425" />
    <xacro:property name="cfr_laser_dz" value="0.5" />
    <xacro:property name="cfr_laser_yaw" value="${pi/4}" />

    <!-- Define robot constants -->
    <xacro:property name="base_width" value="1.0"/>
    <xacro:property name="base_length" value="2.0"/>
    <xacro:property name="base_height" value="0.4"/>

    <xacro:macro name="cfr" params="prefix">

        <!-- Robot Footprint -->
        <link name="base_footprint" />

        <!-- Robot Base -->
        <link name="base_link">
            <!-- <visual>
                <origin xyz="0 0 ${base_height/2}" rpy="0 0 0"/>
                <geometry>
                  <box size="${base_length} ${base_width} ${base_height}"/>
                </geometry>
            </visual> -->

            <!-- <collision>
                <origin xyz="0 0 0" rpy="0 0 0"/>
                <geometry>
                  <box size="${base_length} ${base_width} ${base_height}"/>
                </geometry>
            </collision> -->

            <inertial>
                <origin xyz="0 0 0" rpy="0 0 ${pi/2}"/>
                <mass value="1"/>
                <inertia
                ixx="1.0" ixy="0.0" ixz="0.0"
                iyy="1.0" iyz="0.0"
                izz="1.0"/>
            </inertial>
        </link>

        <joint name="base_joint" type="fixed">
            <parent link="base_footprint"/>
            <child link="base_link"/>
            <origin xyz="0.0 0.0 0.0" rpy="0 0 ${pi/2}"/>
        </joint>

        <link name="cfr_link">
            <collision>
                <origin rpy="0 0 0" xyz="0 0 ${base_height/2}"/>
                <geometry>
                    <box size="${base_length} ${base_width} ${base_height}"/>
                </geometry>
            </collision>

            <visual>
                <origin rpy="${pi/2} 0 0" xyz="-0.0000 -0.01 0.05"/>
                <geometry>
                    <!-- <mesh filename="file://$(find cfr_description)/meshes/cfr_body_without_blades.dae"/> -->
                    <mesh filename="file://$(find cfr_description)/meshes/cfr_v2_body_without_blades.stl" scale="0.001 0.001 0.001"/>
                </geometry>
            </visual>

            <inertial>
                <origin xyz="0 0 0" rpy="0 0 0"/>
                <mass value="10"/>
                <inertia
                ixx="10.0" ixy="0.0" ixz="0.0"
                iyy="10.0" iyz="0.0"
                izz="10.0"/>
            </inertial>
        </link>

        <joint name="cfr_joint" type="fixed">
            <parent link="base_link"/>
            <child link="cfr_link"/>
            <origin xyz="0.0 0.0 0.0" rpy="0 0 0"/>
        </joint>

        <gazebo>
            <plugin name="gazebo_ros_planar_move" filename="libgazebo_ros_planar_move.so">
                <robotNamespace>cfr</robotNamespace>
                <commandTopic>cmd_vel</commandTopic>
                <odometryTopic>odom</odometryTopic>
                <odometryFrame>odom</odometryFrame>
                <odometryRate>20.0</odometryRate>
                <publish_odom>true</publish_odom>
                <publish_odom_tf>true</publish_odom_tf>
                <robotBaseFrame>base_footprint</robotBaseFrame>
            </plugin>
        </gazebo>

        <xacro:laser link="front_left_laser_link" />
        <joint name="base_link_to_front_left_laser_joint" type="fixed">
            <parent link="base_link" />
            <child link="front_left_laser_link" />
            <origin xyz="${cfr_laser_dx} ${-cfr_laser_dy} ${cfr_laser_dz+0.05}" rpy="0 0 ${-cfr_laser_yaw}" />
        </joint>

        <xacro:laser link="back_right_laser_link" />
        <joint name="base_link_to_back_right_laser_joint" type="fixed">
            <parent link="base_link" />
            <child link="back_right_laser_link" />
            <origin xyz="${-cfr_laser_dx} ${cfr_laser_dy} ${cfr_laser_dz+0.25}" rpy="0 0 ${cfr_laser_yaw+pi/2}" />
        </joint>

    </xacro:macro>

</robot>
