cfr:
  teleop_twist_joy_node:
    ros__parameters:
      axis_linear:
        x: 3
        y: 0
      scale_linear:
        x: -3.0
        y: -3.0
      axis_angular:
        yaw: 2
      scale_angular:
        yaw: -1.2
      enable_button: 0
      enable_turbo_button: 6
      require_enable_button: false
